// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PomeloPrimaryKeyBug;

namespace PomeloPrimaryKeyBug.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20210315180105_ChangeDbTrekkTemplateUserKey")]
    partial class ChangeDbTrekkTemplateUserKey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("PomeloPrimaryKeyBug.DbTrekkTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tasks_id");

                    b.HasKey("Id");

                    b.ToTable("tasks");
                });

            modelBuilder.Entity("PomeloPrimaryKeyBug.DbTrekkTemplateUser", b =>
                {
                    b.Property<int>("TrekkTemplateId")
                        .HasColumnType("int")
                        .HasColumnName("TrekkTemplateId");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int")
                        .HasColumnName("WorkerId");

                    b.HasKey("TrekkTemplateId", "WorkerId");

                    b.HasIndex("WorkerId");

                    b.ToTable("tasks_workers");
                });

            modelBuilder.Entity("PomeloPrimaryKeyBug.DbWorker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("workers_id");

                    b.HasKey("Id");

                    b.ToTable("workers");
                });

            modelBuilder.Entity("PomeloPrimaryKeyBug.DbTrekkTemplateUser", b =>
                {
                    b.HasOne("PomeloPrimaryKeyBug.DbTrekkTemplate", "TrekkTemplate")
                        .WithMany()
                        .HasForeignKey("TrekkTemplateId")
                        .HasConstraintName("TemplateContainsTemplateWorkers")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PomeloPrimaryKeyBug.DbWorker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .HasConstraintName("WorkerContainsTemplateWorkers")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrekkTemplate");

                    b.Navigation("Worker");
                });
#pragma warning restore 612, 618
        }
    }
}
